version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]

      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
